"""create borrow records table

Revision ID: 52d9bcefb08e
Revises: fa920785406b
Create Date: 2026-09-15 15:21:38.898543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d9bcefb08e'
down_revision: Union[str, Sequence[str], None] = 'fa920785406b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "borrow_records",
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('borrow_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###
    op.create_index(
        "uq_borrow_records_active_book",
        "borrow_records",
        ["book_id"],
        unique=True,
        postgresql_where=sa.text("return_date IS NULL"),
    )

# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('borrow_records')
#     # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_index(
        "uq_borrow_records_active_book",
        table_name="borrow_records",
    )
    op.drop_table("borrow_records")